### PR TITLE
Update flink `README.md`

### PR DESCRIPTION
**Pull request by scottsand-db**
- add table of contents
- remove java boilerplate from flink examples
- add two flink source examples, one for bounded + time travel, one for continuous + time travel
- have distinct flink sink and flink source sections. each section has its own examples
- misc fixes (e.g. make the known limitation only for 0.4.x, indentation, etc).

### CODE REVIEW

File: flink/README.md [hunk 1]
```diff
@@ -21,53 +38,236 @@ Depending on the version of the connector you can use it with following Apache F
 |  0.4.x (Sink Only)  |    >= 1.12.0    |
 |        0.5.x        |    >= 1.13.0    |
```
Comment (kristoffSC) [inline flink/README.md:39]: 0.5.0 would be
`1.13.0 <= X <=1.14.5`

Comment (scottsand-db) [reply flink/README.md:39]: are there any restrictions on the sink? does it work with flink 1.15 ?

Comment (kristoffSC) [reply flink/README.md]: I would have to check this, because I was using a job with source and sink.
However for sure there are some issues with the connector with this version.

The 1.14.x branch seems ok for both source and sink though.

Comment (kristoffSC) [reply flink/README.md]: @scottsand-db Ive checked a Sink only job with Flink 1.15 and it fails with 
`Caused by: java.lang.NoSuchMethodError: 'org.apache.flink.metrics.MetricGroup org.apache.flink.api.connector.sink.Sink$InitContext.metricGroup()'`

I would say its an issue with incompatible API in Flink 1.15
